spring.application.name=multidatabaseservice

# MySQL 
spring.mysql.datasource.jdbc-url=jdbc:mysql://localhost:3306/spring_boot_microservices_90
spring.mysql.datasource.username=root
spring.mysql.datasource.password=admin
spring.mysql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# postgres
spring.pgdb.datasource.jdbc-url=jdbc:postgresql://localhost:5432/spring_boot_microservices_90_pg
spring.pgdb.datasource.username=postgres
spring.pgdb.datasource.password=admin
spring.pgdb.datasource.driver-class-name=org.postgresql.Driver

# common for both
spring.jpa.hibernate.ddl-auto=update
